
from langchain_google_genai import ChatGoogleGenerativeAI
from langfuse import Langfuse
from langfuse.langchain import CallbackHandler
import os
from langchain_core.messages import HumanMessage, SystemMessage

from src.utils.load_settings import load_yaml, load_env
from src.utils.logger_config import create_logger
from src.utils.image_utils import encode_image_to_base64


config = load_yaml("config/main.yaml")
prompts = load_yaml("prompts/main.yaml")
gcp_config, lf_config = load_env()
logger = create_logger("Descriptions")

Langfuse(
    public_key=lf_config.langfuse_public_key,
    secret_key=lf_config.langfuse_secret_key,
    host=lf_config.langfuse_base_url
)

langfuse_handler = CallbackHandler()


def generate_description(element_type: str, element_content: str = "") -> str:
    """Generate a search-optimized textual description for a table or an image.

    Args:
        element_type: The category of the element ('Table' or 'Image').
        element_content: The raw text/markdown string for a 
            Table, or the local file path string for an Image. Defaults to "".

    Returns:
        str: The detailed description generated by the Gemini model.
    """
    llm = ChatGoogleGenerativeAI(
        model=config["models"]["desc_model"],
        location="global",
        vertexai=True,
        project=gcp_config.project_id,
        timeout=90,
        max_retries=2
    )
    logger.info("Preparing prompt...")
    
    if element_type == "Table":
        system_prompt = prompts["desc_llm"]["system_prompt_table"]
        messages = [
            SystemMessage(content=system_prompt),
            HumanMessage(content=prompts["desc_llm"]["user_prompt_table"].format(element_content=element_content))
        ]
        
    elif element_type == "Image":
        system_prompt = prompts["desc_llm"]["system_prompt_image"]
        
        if not element_content or not os.path.exists(element_content):
            logger.error("Error: Image does not exist.")
            raise FileNotFoundError("Error: Image does not exist.")            
        base64_image = encode_image_to_base64(element_content)
        
        messages = [
            SystemMessage(content=system_prompt),
            HumanMessage(
                content=[
                    {
                        "type": "text", 
                        "text": prompts["desc_llm"]["user_prompt_image"]
                    },
                    {
                        "type": "image_url",
                        "image_url": f"data:image/jpeg;base64,{base64_image}"
                    }
                ]
            )
        ]
    else:
        return ""
    
    logger.info("Invoking model...")
    try:
        response = llm.invoke(messages, config={"callbacks": [langfuse_handler]})
        logger.info("Description generated successfully.")
        if isinstance(response.content, list):
            return response.content[0]["text"]
        return response.content
    except Exception as e:
        logger.warning(f"LLM generation failed for this {element_type} due to timeout/error: {str(e)}. ")
        if element_type == "Table":
            return f"Raw table text (Fallback due to LLM timeout):\n{element_content}"
        return "Image element (Description unavailable due to LLM timeout)."
