models:
  main_model: gemini-3.5-flash
  embedding_model: text-embedding-005
  judge_model: gemini-3.5-flash

retriever:
  top_k: 20
  distance_treshold: 0.3

vector_db:
  knowladge_path: knowladge_base/ifc-annual-report-2024-financials.pdf
  db_path: ./chroma_db
  chunk_size: 1000
  chunk_overlap: 200

evaluation:
  dataset_path: evaluation/input/RAG_evaluation_dataset.csv

