models:
  main_model: gemini-3.5-flash
  embedding_model: text-embedding-005
  judge_model: gemini-3.5-flash
  desc_model: gemini-3.5-flash
  metadata_model: gemini-2.5-fash
  visual_model: vidore/colqwen2-v1.0

retriever:
  top_k: 5
  distance_treshold: 0.3
  highlighted_regions: False                              # True / False (only for visual_multimodal approach)
  highlighted_pages: 3


vector_db:
  # paths
  knowladge_path: knowledge/ifc-annual-report-2024-financials.pdf
  db_path: nic
  interim_images_dir: images/pages
  colpali_index_name: visual_colpali_index

  # parameters
  chunk_size: 3000
  chunk_overlap: 500
  similarity_metric: "cosine"

  # approaches
  chunk_approach: visual_multimodal                          # baseline / multimodal_inline / multimodal_inline_metadata / multimodal_split / visual_multimodal / visual_database
  provider: chroma                                          # chroma / qdrant / faiss
  qdrant_collection_name: multimodal_inline_3000_metadata
  elements_blacklist: []                                    # e.g. ["Image", "Table"] (Only for multimodal apporaches!)


reranker:
  use_reranker: False                                       # True/False
  top_n: 15

